#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers only on updates
if [ ! -e "/usr/local/david/data/users/" ]; then
	exit
fi

# Prevent running and causes issues with outdated david version
if ! id "davidweb" &> /dev/null; then
	exit
fi

# Touch and set permisions on default log files on installation
update-rc.d david defaults > /dev/null
invoke-rc.d david start || true

# Adapt Port Listing in HESTIA NGINX Backend
source /usr/local/david/func/syshealth.sh # Load syshealth functions

# Check if the function syshealth_adapt_david_nginx_listen_ports exists
if ! declare -f syshealth_adapt_david_nginx_listen_ports > /dev/null; then
	exit
fi
syshealth_adapt_david_nginx_listen_ports # Adapt port listing
syshealth_adapt_nginx_resolver

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$HESTIA" ]; then
	export HESTIA='/usr/local/david'
	PATH=$PATH:/usr/local/david/bin
	export PATH
fi

# Check if preinstall hook exists
if [ -e "/etc/davidcp/hooks/nginx/pre_install.sh" ]; then
	/etc/davidcp/hooks/nginx/pre_install.sh
fi

# Load upgrade functions and variables
source /usr/local/david/func/main.sh
source /usr/local/david/func/upgrade.sh
source /usr/local/david/conf/david.conf
source /usr/local/david/install/upgrade/upgrade.conf

# Reset backend port
if [ -n "$BACKEND_PORT" ]; then
	/usr/local/david/bin/v-change-sys-port $BACKEND_PORT
fi

if [ -e "/etc/davidcp/hooks/nginx/post_install.sh" ]; then
	/etc/davidcp/hooks/nginx/post_install.sh
fi

# Restart david service
if [ -f "/etc/init.d/david" ]; then
	systemctl restart david > /dev/null 2>&1
fi
