#!/bin/bash

# David Control Panel upgrade script for target version 1.3.3

#######################################################################################
#######                      Place additional commands below.                   #######
#######################################################################################

# Check if keys folder exists and adjust permissions
if [ -d "$HESTIA/data/keys" ]; then
	echo '[ * ] Update permissions'
	chmod 750 "$HESTIA/data/keys"
	chown admin:root "$HESTIA/data/keys"
fi

if [[ ! -e /etc/davidcp/david.conf ]]; then
	echo '[ * ] Create global David config'

	mkdir -p /etc/davidcp
	echo -e "# Do not edit this file, will get overwritten on next upgrade, use /etc/davidcp/local.conf instead\n\nexport HESTIA='/usr/local/david'\n\n[[ -f /etc/davidcp/local.conf ]] && source /etc/davidcp/local.conf" > /etc/davidcp/david.conf
fi
