#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/david/data/users/admin" ]; then
	exit
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$DAVID" ]; then
	export DAVID='/usr/local/david'
	PATH=$PATH:/usr/local/david/bin
	export PATH
fi

# Load upgrade functions and variables
source /usr/local/david/func/main.sh
source /usr/local/david/func/upgrade.sh
source /usr/local/david/conf/david.conf
source /usr/local/david/install/upgrade/upgrade.conf

# Restart david-web-terminal service if enabled
if [ -f "/etc/systemd/system/david-web-terminal.service" ]; then
	systemctl daemon-reload > /dev/null 2>&1
	if systemctl is-enabled david-web-terminal > /dev/null 2>&1; then
		systemctl restart david-web-terminal
	fi
fi
